#!/bin/sh +x
# trap ctrl-c and call ctrl_c()
trap 'rm -f /dev/shm/cm_abort* /dev/shm/ssmp_* /dev/shm/tm2c_*;
killall $(basename $PROG) >> /dev/null; echo "** cleaned-up"; exit 1' INT

if [ $# -lt 2 ];
then
    echo "Usage: $0 NUM_CORES PROGRAM [PARAMS]"
    exit 1;
fi

NUM_CORES=$1;
shift;
PROG=$1;
shift;

echo "running: $PROG on $NUM_CORES cores with params: $@";
./$PROG -total=$NUM_CORES $@
