#!/bin/sh

N=2;
STEP=1;
M=6;

if [ $# -eq 3 ]; then
    M=$1;
    shift;
elif [ $# -eq 4 ]; then
    N=$1;
    shift;
    M=$1;
    shift;
elif [ $# -eq 5 ]; then
    N=$1;
    shift;
    STEP=$1;
    shift;
    M=$1;
    shift;
elif [ $# -eq 2 ]; then
    N = 2; 			# dummy
else
    echo "Usage: $0 [starting_core] [step] [ending_core] program \"parameters\"";
    echo "       Ex. $0 2 4 48 bmarks/bank \"-d2 -r0\"";
fi

app=$1;
shift;

echo "#nue     Throughput CRate  Latency NumDSL Th/nue  Th/dsl";

for nue in `seq $N $STEP $M`; do
    printf "$nue\t";
    RES=`./run $nue $app $@ | grep ")))" | sed 's/)//g' | cut -d"(" -f1`;
    printf "$RES";
    TH=`echo $RES | cut -d' ' -f1`;
    NUM_DSL=`echo $RES | cut -d' ' -f4`;
    printf "%8.0f%8.0f\n" `echo $TH/$nue | bc -l` `echo $TH/$NUM_DSL | bc -l`;
done
