#!/bin/sh

num_params=$#;

repetitions=3;
out="out.runrrep";

if [ -f  $out ]; then
    rm $out;
fi


if [ $# -lt 2 ]; then
    echo "Usage: runrrep REPETITIONS PROGRAMS [PARAMETERS] [PARAMETERSinsteadofcores] [numcores]";
    echo "";
    echo "run repeatedly (from 2..48 cores) using many (default $repetitions) repetitions;";
    echo "output can be collected using collect[.].awk from $out file";
else
    repetitions=$1;
    shift;
    progs=$1;
    shift;
    params="$@";
    if [ $num_params -lt 4 ]; then
	for nue in 2 4 8 16 32 48; do
	    echo $nue
	    for prog in $progs; do
		echo $prog " " $params;
		./runrep_ $prog $nue $repetitions $params >> $out;
	    done
	done
    else
	nue=48;
	if [ $num_params -eq 5 ]; 
	then
	    nue=$3;
	fi

	fixed_params="$1";
	shift;
	params="$1";

	for par in $params; 
	do
	    use_param="$fixed_params $par";
	    for prog in $progs; 
	    do
		echo $prog " " $use_param;
		./runrep_ $prog $nue $repetitions $use_param >> $out;
	    done
	done
    fi
fi

exit