#!/bin/sh

slog="runrep_.log";

if [ -f $slog ]; then
    rm $slog;

fi


if [ $# -lt 2 ]; then
    echo "Usage: runrep PROGRAM NUMCORES [REPETITIONS] [PARAMS]"

else
    prog=$1;
    shift;
    ues=$1;
    shift;
    if [ $1" " != " " ]; then
	reps=$1;
	shift;
    else
	reps=5;
    fi

    i=0;
    while [ "$i" -lt "$reps" ]
    do
	./run $ues ./$prog $@ >> $slog;
	echo i;
        i=$(expr $i + 1)
    done

#    for (( i=1; i<=reps; i++ ))
#    do
#	
#    done
    
    awk -f runrep_.awk $slog;
    

fi


exit