CCOMPILE=/opt/csw/bin/gcc -m64

PLATFORM_CFLAGS = -O3 -mcpu=v9 -mtune=v9
PLATFORM_LDFLAGS = 
PLATFORM_LIBS = -lssmp -lrt

## fixed defines
PLATFORM_DEFINES +=    -DPLATFORM_NIAGARA \
		       -DSSMP

ARCHIVE_SRCS_PURE += tm2c_malloc.c
ARCHIVE_SRCS_PURE += sys_niagara.c

#same as cluster, non-pgas experiments will not work
ALL_BMARKS = bank mbll ht
