RCCEPATH=/opt/src/RCCE_src/rcce
SYMBOLSPATH=$(RCCEPATH)/common/symbols

API          := gory

-include $(SYMBOLSPATH)

PLATFORM_CFLAGS = -O3
PLATFORM_LDFLAGS = 
PLATFORM_LIBS = -lssmp

## fixed defines
PLATFORM_DEFINES +=     -DPLATFORM_SCC \
		   	-DSSMP

ARCHIVE_SRCS_PURE += sys_scc.c

INCLUDES += -I$(RCCEPATH)/include
